# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LearnEnvoy
email: learnenvoy@turbinelabs.io
support_email: learnenvoy@turbinelabs.io
description: > # this means to ignore newlines until "baseurl:"
  LearnEnvoy is a community content site that helps organizations get the most
  out of the Envoy proxy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.learnenvoy.io"
twitter_username: goturbine
github_username:  turbinelabs

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
theme: agency-jekyll-theme

collections:
  articles:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - CODE_OF_CONDUCT.md
  - LICENSE
  - README.md
  - vendor/bundler
  - node_modules
  - Makefile
sass:
  load_paths:
    - _sass
    - node_modules

gems:
  - jekyll-sitemap
